name: UI Tests - SauceDemo

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build Docker image
              run: docker build -t saucedemo-tests .

            - name: Run tests
              run: |
                docker run \
                  -v ${{ github.workspace }}/reports:/app/reports \
                  saucedemo-tests \
                  pytest -v --html=reports/report.html --self-contained-html

            - name: Upload report
              uses: actions/upload-artifact@v4
              if: always()
              with:
                name: test-report
                path: report.html
  
    
